# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Jeremy Lacomis
description:      "Jeremy Lacomis' homepage."
baseurl:          ""

author:
  name:           'Jeremy Lacomis'
  # url:            https://www.cs.cmu.edu/~jlacomis

# paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins: ['jekyll/scholar']

# Custom vars
# version:            3.4.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/jlacomis

twitter: https://twitter.com/jlacomis

scholar:
  style: bib.csl
  source: ./_bibliography
  bibliography: references.bib
  bibtex_skip_fields: ['abstract', 'code', 'data', 'month_numeric', 'results',
  'tool', 'slides']
  repository: materials
  sort_by: year, month
  group_order: descending
  bibliography_template: bib_template

# exclude: "list of files to exclude"
