name: Build and Deploy
on:
  push:
    branches:
      - update

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Install and Build
        run: |
          gem install bundler -v 2.4.22
          bundle exec jekyll build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: _site
